name: Bump flake.lock

on:
  schedule:
    # Starting at midnight (4am UTC)
    - cron: "10 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: native

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot
          commit_user_email: flakebot@ptinem.casa
          commit_author: Flake Bot <flakebot@ptinem.casa>
          skip_dirty_check: false    
          skip_fetch: true
