---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

# vars:

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  test:
    desc: Rebuild the OS as a test
    cmds:
      - sudo nixos-rebuild test --flake '.#'

  switch:
    desc: Rebuild the OS and switch
    cmds:
      - sudo nixos-rebuild switch --flake '.#'